export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const CART_CAKE_ROUTE = '/cart'
export const ORDER_ROUTE = '/order'
export const MAIN_SHOP_ROUTE = '/cakes'